// Generated by Wrangler on Fri Aug 23 2024 23:39:38 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	SESSION_KV: KVNamespace;
	HASURA_ENDPOINT: string;
	HASURA_ADMIN_SECRET: string;
	LIFF_ID: string;
}
