// Generated by Wrangler on Sun Aug 25 2024 00:29:41 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	SESSION_KV: KVNamespace;
	LIFF_ID: "";
	HASURA_ENDPOINT: string;
	HASURA_ADMIN_SECRET: string;
}
